### ISSUE TITLE
storj-billing burns the CPU

### ISSUE THREAD

**Issue by kaloyan-raev** [Storj/integration#10]
I noticed that if I "start everything" and leave the container idle, it consumes ~30% of my laptop CPU power.

As far as I can see this is caused by short-living `storj-billing` processes. When the `storj-billing` process finishes, another one is immediately launched. It would be nice to have some delays between the runs.

**Comment by braydonf** [comment]
There is likely a configuration value missing, and causing it to crash.

**Comment by kaloyan-raev** [comment]
For sure I haven't set a valid `STRIPE_KEY` in `./config/storj-billing/config`, because I don't really want to test the Bridge GUI. Could this be the cause?

**Comment by braydonf** [comment]
Yeah, most likely. Probably best to disable it for the time being.

**Comment by kaloyan-raev** [comment]
Yes. This is what I have just done.

**Comment by RichardLitt** [comment]
Thanks all. 

I'm closing this issue as it hasn't seen activity in a while, as this repository is now deprecated and unmaintained, and as we're moving towards v3 at [storj/storj](https://github.com/storj/storj).
