### ISSUE TITLE
storj mailer isn't sending an email

### ISSUE THREAD

**Issue by nfarah86** [Storj/integration#12]
In ./config/storj-bridge/config.json, you have the option to edit this json to something like this

  "mailer": {
    "host": "smtp.gmail.com",
    "port": 465,
    "secure": true,
    "auth": {
      "user": "storjtestuser@gmail.com",
      "pass": "the password"
    },

when I check storjtestuser email, nothing was sent.  I can fix this later-  when I get some downtime. Just wanted to create an issue before I forget.

**Comment by RichardLitt** [comment]
Thanks @nfarah86. 

I'm closing this issue as it hasn't seen activity in a while, as this repository is now deprecated and unmaintained, and as we're moving towards v3 at [storj/storj](https://github.com/storj/storj).
