### ISSUE TITLE
"hdIndex" is expected with "hdKey"

### ISSUE THREAD

**Issue by onsightit** [Storj/integration#4]
I am in the process of setting up a testnet with 15 farmers, and I came across this integration repo.  In trying to setup the complex, I get the following error:

AssertionError: "hdIndex" is expected with "hdKey"

I looked at the code and it appears I need to generate HD keys for the renters, but I cannot find any online references on how to generate the complex private key.  Can you shed some light on this for me?

Thanks,
Steve

**Comment by braydonf** [comment]
- https://github.com/Storj/complex/issues/41
- https://github.com/Storj/complex#generating-an-hd-key

**Comment by onsightit** [comment]
Thanks, also, it appears that you should not use a NetworkIndex of '0' in the config.

**Comment by braydonf** [comment]
Yeah, we need to fix that.

**Comment by RichardLitt** [comment]
Thanks all. 

I'm closing this issue as it hasn't seen activity in a while, as this repository is now deprecated and unmaintained, and as we're moving towards v3 at [storj/storj](https://github.com/storj/storj).
